# fly.toml app configuration file generated for coreyja on 2023-05-20T16:18:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "coreyja-status"
primary_region = "ewr"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
OTEL_SERVICE_NAME = "status"

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1
max_machines_running = 2

[[http_service.checks]]
interval = "30s"
timeout = "2s"
grace_period = "5s"
path = "/"
